image: gradle:7.2

stages:
  - sample-stage

sample-job:
  stage: sample-stage
  script:
    - gradle clean build --info -Pversion="${CI_PIPELINE_ID}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}"
  artifacts:
    paths:
      - domain/build/libs/*.jar
      - persistence/build/libs/*.jar
      - api/build/libs/*.jar