image: gradle:7.2

variables:
  JACOCO_CSV_LOCATION: '$CI_PROJECT_DIR/domain/build/jacocoCsv'

stages:
  - sample-stage

sample-job:
  stage: sample-stage
  coverage: '/    - Line Coverage: ([0-9.]+)%/'
  script:
    - gradle clean build --info -Pversion="${CI_PIPELINE_ID}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}"
#    - pwd
    - /builds/rbakker/mancala-java/calculate-coverage.sh
  artifacts:
    paths:
#      - build/reports/jacoco/test/html/
      - domain/build/libs/*.jar
      - persistence/build/libs/*.jar
      - api/build/libs/*.jar