variables:
  BUILD_ID: "${CI_CONCURRENT_ID}"
  BRANCH: "${CI_COMMIT_BRANCH}"
  COMMIT_SHA: "${CI_COMMIT_SHA}"

image: gradle:7.2

stages:
  - sample-stage

sample-job:
  stage: sample-stage
  script:
    - gradle clean build --info -Pversion="${BUILD_ID}-${BRANCH}-${COMMIT_SHA}"
  artifacts:
    paths:
      - domain/build/libs/*.jar