image: gradle:7.2

variables:
  JACOCO_CSV_LOCATION: '$CI_PROJECT_DIR/domain/build/jacocoCsv'

stages:
  - test
#  - build

test:
  stage: test
  coverage: '/Average Coverage: ([0-9.]+)%/'
  script:
#    - chmod +x /builds/rbakker/mancala-java/testandreportcoverage.sh
#    - /builds/rbakker/mancala-java/testandreportcoverage.sh
    - pwd
    - ls
    - ls ..
    - ls ../..
    - ls ../../..

#  artifacts:
#    paths:
#      - domain/build/reports
#      - api/build/reports
#      - persistence/build/reports
#
#build:
#  stage: build
#  script:
#      - ./gradlew clean build -Pversion="${CI_PIPELINE_ID}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}"
#
#  artifacts:
#    paths:
#        - domain/build/libs/*.jar
#        - persistence/build/libs/*.jar
#        - api/build/libs/*.jar
#        - client/