BUILD_ID: "${CI_CONCURRENT_ID}"

image: gradle:7.2

stages:
  - sample-stage

sample-job:
  stage: sample-stage
  script:
    - gradle clean build --info -Pversion="${BUILD_ID}"
  artifacts:
    paths:
      - domain/build/libs/*.jar