image: gradle:7.2

variables:
  JACOCO_CSV_LOCATION: '$CI_PROJECT_DIR/domain/build/jacocoCsv'

stages:
  - build

build:
  stage: build
  coverage: '/Average Coverage: ([0-9.]+)%/'
  script:
    - chmod +x /builds/rbakker/mancala-java/buildandreportcoverage.sh
    - /builds/rbakker/mancala-java/buildandreportcoverage.sh

  artifacts:
    paths:
      - domain/build/libs/*.jar
      - persistence/build/libs/*.jar
      - api/build/libs/*.jar
      - client/
      - domain/build/reports
      - api/build/reports
      - persistence/build/reports