#variables:
#  BUILD_ID: "${CI_CONCURRENT_ID}"
#  BRANCH: "${CI_COMMIT_BRANCH}"
#  COMMIT_SHA: "${CI_COMMIT_SHA}"

image: gradle:7.2

stages:
  - sample-stage

sample-job:
  stage: sample-stage
  script:
    - gradle clean build --info -Pversion="${CI_CONCURRENT_ID}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}"
  artifacts:
    paths:
      - domain/build/libs/*.jar